- hosts: all
  tasks:
    - pip:
        name: openshift

    - name: Create a k8s namespace
      k8s:
        name: group01
        api_version: v1
        kind: Namespace

    - name: Create a Deployment for backend-service
      k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: cc-backend-service
            namespace: group01
          spec:
            selector:
              matchLabels:
                app: cc-backend-service
            replicas: 6
            template:
              metadata:
                labels:
                  app: cc-backend-service
              spec:
                containers:
                  - name: cc-backend-service
                    image: jannoh/janno:backend
                    ports:
                      - name: backend-port
                        containerPort: 80

    - name: Create a Service object for backend-service
      k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: cc-backend-service
            namespace: group01
            labels:
              app: cc-backend-service
          spec:
            ports:
              - protocol: TCP
                port: 80
                targetPort: backend-port
            selector:
              app: cc-backend-service

    - name: Create a Deployment for frontend-service
      k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: cc-frontend-service
            namespace: group01
          spec:
            selector:
              matchLabels:
                app: cc-frontend-service
            replicas: 4
            template:
              metadata:
                labels:
                  app: cc-frontend-service
              spec:
                containers:
                  - name: cc-frontend-service
                    image: jannoh/janno:frontend




    - name: Create a Service object for frontend-service
      k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: cc-frontend-service
            namespace: group01
            labels:
              app: cc-frontend-service
          spec:
            type: NodePort
            ports:
              - port: 80
                targetPort: 80
                protocol: TCP
            selector:
              app: cc-frontend-service
